MIT-Emerging-Talent/ET6-CDSP-group-09-repo

collaboration/constraints.md

adding the group constraints

---

collaboration/learning_goals.md

Add and update the collaboration learning goals file

---

collaboration/learning_goals.md

update the Title

---

.vscode/settings.json
collaboration/retrospective.md

updating individual retro 

---

notes/meeting_minutes/meeting_04.md

Add meeting-4 minutes

---

notes/meeting_minutes/meeting_05.md

Meeting 5 minutes

---

notes/meeting_minutes/meeting_06.md

add meeting 6 minutes

---

collaboration/retrospectives/1_problem_identification.md

Add the Retrospective

---

README.md
collaboration/communication.md
collaboration/learning_goals.md

Mohamed learning goals

---

README.md

fix the shape of members in main README

---

notes/meeting_minutes/meeting_12.md

Adding meeting minutes 12

---

0_domain_study/problem_statement.md

Add updated problem statement

---

README.md

Repo readme enhance

---

collaboration/retrospectives/2_data_collection.md

add retrospectives for milestone 2

---

3_data_exploration/README.md

fix data exploration title

---

notes/meeting_minutes/meeting_13.md

Add meeting 13 minutes

---

notes/meeting_minutes/meeting_14.md

Meeting 14 minutes

---

notes/meeting_minutes/meeting_15.md

add meeting 15 minutes

---

4_data_analysis/covid_mortality_technical_explanation.md
4_data_analysis/pm25_health_technical_explanation.md

Technical explanation

---

README.md

Add Non technical explanation of data analysis

---

README.md

added the typing svg for saliha's titles

---

2_data_preparation/README.md
3_data_exploration/README.md

editing the data exploration and data preparation readmes with new links

---

notes/meeting_minutes/meeting_22.md

---
Add meeting 22 minutes
---

Add meeting 22 minutes

---

notes/meeting_minutes/meeting_23.md

add 23rd meeting minutes

---

notes/meeting_minutes/meeting_24.md

meeting 24 minutes

---

5_communication_strategy/target_audience.md

Describe target audience

---

notes/meeting_minutes/meeting_25.md

meeting 25 minutes

---

notes/meeting_minutes/meeting_25.md
notes/meeting_minutes/meeting_26.md

Meeting 26

---

notes/meeting_minutes/meeting_27.md

Meeting 27
